const mongoose = require('mongoose');

const calendarEventSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    title: { type: String, required: true },
    date: { type: String, required: true },   // "YYYY-MM-DD"
    time: { type: String, default: null },    // "3:00 PM IST"
    type: {
      type: String,
      enum: ['interview', 'assessment', 'follow_up', 'offer_expiry', 'deadline', 'join_date', 'meeting', 'custom'],
      default: 'custom',
    },
    company: { type: String, default: '' },
    role: { type: String, default: '' },
    status: { type: String, default: '' },
    notes: { type: String, default: '' },
    sourceEmailId: { type: mongoose.Schema.Types.ObjectId, ref: 'SyncedEmail', default: null },
    applicationId: { type: mongoose.Schema.Types.ObjectId, ref: 'Application', default: null },
    isAutoGenerated: { type: Boolean, default: false },
    sourceText: { type: String, default: '' },
    completed: { type: Boolean, default: false },
    color: { type: String, default: '' },
  },
  { timestamps: true }
);

calendarEventSchema.index({ userId: 1, date: 1 });

module.exports = mongoose.model('CalendarEvent', calendarEventSchema);